### PR TITLE
Fix failure of calling authenticated APIs when multiple AsgardeoProvider instances are used

### LINKED ISSUE #329: bug: Fails Authenticated API Calls When Multiple AsgardeoProvider Instances Are Used
### Description

When an application utilizes multiple instances of the AsgardeoProvider component, typically to support concurrent logins for different users or organizations within the same frontend application, authenticated API calls triggered via the SDK fail.

It appears that the SDK may not be correctly isolating the authentication state (tokens, HTTP client instances, or storage keys) between the different provider contexts. This results in the httpRequest or related API helpers failing to attach the correct Authorization header, or using the wrong token context.

### Steps to Reproduce

1. Initialize a React application.
2. Wrap two different parts of the component tree with distinct AsgardeoProvider instances (e.g., Provider A for Org A and Provider B for Org B), configured with different credentials and scopes.
3. Authenticate a user successfully in Provider A.
4. Authenticate a different user successfully in Provider B.
5. Attempt to make a secure API call using the httpRequest method from within a component wrapped by Provider B (or Provider A).

### Please select the area the issue is related to

@asgardeo/react, @asgardeo/browser, @asgardeo/javascript

### Version

N/A

### Environment Details (with versions)

_No response_

### Reporter Checklist

- [x] I have searched the existing issues and this is not a duplicate.
- [x] I have provided all the necessary information.
- [x] I have tested the issue on the latest version of the package.

### PR DESCRIPTION
**Pull request by kavindadimuthu**
This pull request introduces adoption of a Multiton pattern in AsgardeoSPAClient, allowing multiple authentication contexts to coexist within the same application by managing client instances via unique IDs. Several React level APIs have been updated to accept and propagate these instance IDs, ensuring correct isolation and management of authentication state per instance.

**Multiton pattern implementation and API updates for instance-awareness::**

* Refactored `AsgardeoSPAClient` in `client.ts` to implement a Multiton pattern, including new static methods for managing instances (`getInstance`, `hasInstance`, `destroyInstance`, `getInstanceKeys`, `destroyAllInstances`), and added an instance ID accessor (`getInstanceId`). [[1]](diffhunk://#diff-06316638f5189aebbdce15caeb5f97566501bb24376fdacfc0036324459f9b59R64-R65) [[2]](diffhunk://#diff-06316638f5189aebbdce15caeb5f97566501bb24376fdacfc0036324459f9b59L173-R190) [[3]](diffhunk://#diff-06316638f5189aebbdce15caeb5f97566501bb24376fdacfc0036324459f9b59L190-R305)
* Updated `AsgardeoReactClient` and all organization-related API functions (`createOrganization`, `getAllOrganizations`, `getMeOrganizations`, `getOrganization`) in React to accept an optional `instanceId` parameter and use the correct client instance for requests. [[1]](diffhunk://#diff-3ef7f64929b67062f02a938790c0445aa7f0672406b29c9022ad23b1881fb746L29-L30) [[2]](diffhunk://#diff-3ef7f64929b67062f02a938790c0445aa7f0672406b29c9022ad23b1881fb746R38-R41) [[3]](diffhunk://#diff-3ef7f64929b67062f02a938790c0445aa7f0672406b29c9022ad23b1881fb746L93-R99) [[4]](diffhunk://#diff-70c8208321a1014090940f55c6931b47ae12a1f0fb6424a48ddfc4d0a97bd756L28-L29) [[5]](diffhunk://#diff-70c8208321a1014090940f55c6931b47ae12a1f0fb6424a48ddfc4d0a97bd756R37-R40) [[6]](diffhunk://#diff-70c8208321a1014090940f55c6931b47ae12a1f0fb6424a48ddfc4d0a97bd756R88-R94) [[7]](diffhunk://#diff-a5ad49da3679e99afb0ca43e225d6edf4ad519bb0fc605f502183eb0f775db67L28-L29) [[8]](diffhunk://#diff-a5ad49da3679e99afb0ca43e225d6edf4ad519bb0fc605f502183eb0f775db67R37-R40) [[9]](diffhunk://#diff-a5ad49da3679e99afb0ca43e225d6edf4ad519bb0fc605f502183eb0f775db67L88-R94) [[10]](diffhunk://#diff-2285b3bde01ccc930dc7913efa9bccc0bc6d83f26e39ce945d7db69293d343c7L28-L29) [[11]](diffhunk://#diff-2285b3bde01ccc930dc7913efa9bccc0bc6d83f26e39ce945d7db69293d343c7R37-R40)

### Related Issues
- Fixes #329 

### Related PRs
- #325 
- #327 

### Checklist
- [ ] Followed the [CONTRIBUTING](https://github.com/asgardeo/javascript/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Manual test round performed and verified.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Review by DonOmalVindula — COMMENTED** [review]
Reviewed the changes. Left some comments. Please address them before merging.

File: packages/browser/src/__legacy__/client.ts [hunk 1]
```diff
@@ -192,22 +201,113 @@ export class AsgardeoSPAClient {
...
+   */
+  public static destroyInstance(id: number = 0): boolean {
+    return this._instances.delete(id);
+  }
 
-    return this._instances.get(0);
+  /**
+   * This method returns all active instance IDs.
+   * Useful for debugging or managing multiple instances.
+   *
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/client.ts]: `@preserve` is only needed on methods that are part of the public API and should survive minification. Debugging/testing utilities like `getInstanceKeys()` and `destroyAllInstances()` don't need it. Remove `@preserve` from these utility methods. For example:

```typescript
  /**
   * This method returns all active instance IDs.
   *
   * @return {number[]} - Returns an array of all active instance IDs.
   *
   * @memberof AsgardeoSPAClient
   */
  public static getInstanceKeys(): number[] {
    return Array.from(this._instances.keys());
  }
```

Apply the same for `destroyAllInstances` and `hasInstance`.

File: packages/browser/src/__legacy__/client.ts [hunk 2]
```diff
@@ -192,22 +201,113 @@ export class AsgardeoSPAClient {
...
+   * @return {boolean} - Returns true if the instance was found and removed.
+   *
+   * @example
+   * ```
+   * // Remove a specific instance
+   * AsgardeoSPAClient.destroyInstance(1);
+   *
+   * // Remove the default instance
+   * AsgardeoSPAClient.destroyInstance();
+   * ```
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/client.ts]: `destroyInstance` only removes the instance from the map. It doesn't clean up the underlying auth state (storage, tokens, session data, etc.) that the instance manages. If someone calls `destroyInstance(1)` and then `getInstance(1)`, they'll get a fresh instance but the old storage data for `instance_1` is still sitting in session/local storage. Suggested fix:

```typescript
  public static destroyInstance(id: number = 0): boolean {
    const instance = this._instances.get(id);
    if (instance) {
      // Clear session/storage data for this instance before removing
      instance.clearSession?.();
    }
    return this._instances.delete(id);
  }
```

Same applies for `destroyAllInstances` — iterate and clean up each instance before clearing the map.

File: packages/react/src/api/getScim2Me.ts [hunk 3]
```diff
@@ -76,8 +78,11 @@ export interface GetScim2MeConfig extends Omit<BaseGetScim2MeConfig, 'fetcher'>
  * }
  * ```
  */
-const getScim2Me = async ({fetcher, ...requestConfig}: GetScim2MeConfig): Promise<User> => {
+const getScim2Me = async ({fetcher, instanceId = 0, ...requestConfig}: GetScim2MeConfig): Promise<User> => {
   const defaultFetcher = async (url: string, config: RequestInit): Promise<Response> => {
+    const httpClient: HttpInstance = AsgardeoSPAClient.getInstance(instanceId).httpRequest.bind(
```
[the remark this answers is not in the document]
Comment (kavindadimuthu) [reply packages/react/src/api/getScim2Me.ts]: Resolved this

File: packages/browser/src/__legacy__/client.ts (hunk 2 above)
Comment (kavindadimuthu) [reply packages/browser/src/__legacy__/client.ts]: Resolved this

File: .changeset/loud-memes-admire.md
Comment (DonOmalVindula) [inline .changeset/loud-memes-admire.md]: Remove the unwanted changeset file
