### PR TITLE
Fix failure of calling authenticated APIs from secondary AsgardeoProvider Instances (Multi-Provider Support)

### LINKED ISSUE #335: bug: Authenticated API Calls Fail for Secondary AsgardeoProvider Instances (Multi-Provider Support)
### Description

In a scenario where multiple AsgardeoProvider components are instantiated within a single application (to support multiple concurrent sessions/organizations), authenticated API calls (httpRequest) only succeed for the first initialized provider.

Attempts to make authenticated requests via the useAuthContext() hook from subsequent (second, third, etc.) AsgardeoProvider instances fail. It appears that the SDK's internal state or the HTTP client instance might be binding to the first provider's configuration and is not correctly switching context for subsequent providers.

### Expected Behavior
The httpRequest method should function correctly for all AsgardeoProvider instances independently. The SDK should isolate the HTTP client, token storage, and configuration for each provider instance, allowing concurrent authenticated calls.

### Actual Behavior

- Provider A (First Instance): API calls function as expected.
- Provider B (Subsequent Instances): API calls fail.

### Steps to Reproduce

1. Initialize a React application.
2. Set up two distinct AsgardeoProvider instances (Provider A and Provider B) with different configurations/scopes.
3. Authenticate successfully using Provider A.
4. Authenticate successfully using Provider B.
5. Execute an authenticated API call using httpRequest from Provider A. -> Result: SUCCESS.
6. Execute an authenticated API call using httpRequest from Provider B. -> Result: FAIL.

### Please select the area the issue is related to

@asgardeo/javascript, @asgardeo/browser, @asgardeo/react

### Version

N/A

### Environment Details (with versions)

_No response_

### Reporter Checklist

- [x] I have searched the existing issues and this is not a duplicate.
- [x] I have provided all the necessary information.
- [x] I have tested the issue on the latest version of the package.

### PR DESCRIPTION
**Pull request by kavindadimuthu**
### Purpose
This pull request introduces multi-HTTP clients support when multiple provider instances are implemented. This ensures that all authenticated HTTP operations are isolated per instance.

The most important changes are:

**Instance-specific HTTP Client Management**
- Refactored `HttpClient` to support multiple isolated HTTP client/axios instances, each keyed by instance ID, preventing state conflicts between auth contexts. All HTTP handler flags and callbacks are now instance-specific. [[1]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L44-R46) [[2]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L69-R113) [[3]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L137-R140) [[4]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L154-R157) [[5]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L174-R177) [[6]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L198-R216) [[7]](diffhunk://#diff-31e4a95cf6112eafb53073c9f5f9190726b4e4bb2ed1fbb59f421cabac93a583L222-R228) [[8]](diffhunk://#diff-a1e877c5e8f55b5b9bde6dd1a86c8e2a24c80d44915d7e468e2987ba64e68a15L26-R26)
- Updated all usages of `HttpClient.getInstance()` to provide the correct instance ID, ensuring HTTP requests are routed through the correct context. [[1]](diffhunk://#diff-94c7315f5dce5e3ab5e61074bcc74e4c48a77af5f8fb2751c51db8dfa0f7847fL88-R88) [[2]](diffhunk://#diff-34b5dcf8d993047dde2c06aa00d5b06b1e4e2173f599f06bf6516fd283e4dc35L171-R186) [[3]](diffhunk://#diff-34b5dcf8d993047dde2c06aa00d5b06b1e4e2173f599f06bf6516fd283e4dc35L202-R216) [[4]](diffhunk://#diff-34b5dcf8d993047dde2c06aa00d5b06b1e4e2173f599f06bf6516fd283e4dc35L224-R238)

### Related Issues
- Fixes #335 

### Related PRs
- #325
- #327
- #334

### Checklist
- [ ] Followed the [CONTRIBUTING](https://github.com/asgardeo/javascript/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Manual test round performed and verified.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 1]
```diff
@@ -41,9 +41,9 @@ import {HttpClientInstance, HttpClientInterface, HttpClientStatic} from '../mode
  */
 @staticDecorator<HttpClientStatic<HttpClientInstance>>()
 export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpResponse, HttpError> {
-  private static axiosInstance: HttpClientInstance;
-  private static clientInstance: HttpClient;
-  private static isHandlerEnabled: boolean;
+  private static instances: Map<number, HttpClientInstance> = new Map();
+  private static clientInstances: Map<number, HttpClient> = new Map();
+  private isHandlerEnabled: boolean = true;
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Better not to set a default value without checking the actual usage of this

Comment (kavindadimuthu) [reply packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Resolved this

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 2]
```diff
@@ -66,48 +66,51 @@ export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpRe
...
+    axiosInstance.enableHandler = clientInstance.enableHandler;
+    axiosInstance.disableHandler = clientInstance.disableHandler;
+    axiosInstance.disableHandlerWithTimeout = clientInstance.disableHandlerWithTimeout;
+    axiosInstance.setHttpRequestStartCallback = clientInstance.setHttpRequestStartCallback;
+    axiosInstance.setHttpRequestSuccessCallback = clientInstance.setHttpRequestSuccessCallback;
+    axiosInstance.setHttpRequestErrorCallback = clientInstance.setHttpRequestErrorCallback;
+    axiosInstance.setHttpRequestFinishCallback = clientInstance.setHttpRequestFinishCallback;
+    
+    this.instances.set(instanceId, axiosInstance);
+    return axiosInstance;
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: `enableHandler`, `disableHandler`, and `disableHandlerWithTimeout` are assigned as bare function references onto the axios instance:

```typescript
axiosInstance.enableHandler = clientInstance.enableHandler;
axiosInstance.disableHandler = clientInstance.disableHandler;
axiosInstance.disableHandlerWithTimeout = clientInstance.disableHandlerWithTimeout;
```

These methods now use `this.isHandlerEnabled` (instance property). When called as `httpClient.enableHandler()`, `this` refers to the **axios instance**, not the `HttpClient` instance — so `this.isHandlerEnabled` reads/writes a property on the wrong object.

In the old singleton code this was masked because `isHandlerEnabled` was `static` (`HttpClient.isHandlerEnabled`) which doesn't depend on `this`. Now that it's an instance property, the broken binding actually matters.

**Fix:** Add these to the constructor's `.bind(this)` calls:

```typescript
private constructor() {
    this.init = this.init.bind(this);
    this.enableHandler = this.enableHandler.bind(this);
    this.disableHandler = this.disableHandler.bind(this);
    this.disableHandlerWithTimeout = this.disableHandlerWithTimeout.bind(this);
    this.setHttpRequestErrorCallback = this.setHttpRequestErrorCallback.bind(this);
    this.setHttpRequestFinishCallback = this.setHttpRequestFinishCallback.bind(this);
    this.setHttpRequestStartCallback = this.setHttpRequestStartCallback.bind(this);
    this.setHttpRequestSuccessCallback = this.setHttpRequestSuccessCallback.bind(this);
}
```

Without this fix, any code calling `httpClient.disableHandler()` or `httpClient.enableHandler()` after `init()` will silently fail to toggle the flag on the correct `HttpClient` instance.

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 3]
```diff
@@ -41,9 +41,9 @@ import {HttpClientInstance, HttpClientInterface, HttpClientStatic} from '../mode
  */
 @staticDecorator<HttpClientStatic<HttpClientInstance>>()
 export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpResponse, HttpError> {
-  private static axiosInstance: HttpClientInstance;
-  private static clientInstance: HttpClient;
-  private static isHandlerEnabled: boolean;
+  private static instances: Map<number, HttpClientInstance> = new Map();
+  private static clientInstances: Map<number, HttpClient> = new Map();
+  private isHandlerEnabled: boolean;
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Nit: `isHandlerEnabled` is declared but not initialized — its value is `undefined` until `init()` is called. This means if any request fires before `init()`, `isHandlerEnabled` is `undefined` (falsy) and all callbacks are silently skipped. The old code had the same issue (static property was also uninitialized), so this isn't a regression, but consider initializing it:

```typescript
private isHandlerEnabled: boolean = true;
```

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts (hunk 2 above)
Comment (kavindadimuthu) [reply packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Resolved this

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 4]
```diff
@@ -41,9 +41,9 @@ import {HttpClientInstance, HttpClientInterface, HttpClientStatic} from '../mode
  */
 @staticDecorator<HttpClientStatic<HttpClientInstance>>()
 export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpResponse, HttpError> {
-  private static axiosInstance: HttpClientInstance;
-  private static clientInstance: HttpClient;
-  private static isHandlerEnabled: boolean;
+  private static instances: Map<number, HttpClientInstance> = new Map();
+  private static clientInstances: Map<number, HttpClient> = new Map();
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: **Dead code:** `clientInstances` is write-only — nothing ever calls `clientInstances.get()`. If you add a `destroyInstance()` method (see my other comment), this map becomes useful for cleanup. Otherwise, it should be removed to avoid confusion.

File: packages/browser/src/__legacy__/clients/main-thread-client.ts [hunk 5]
```diff
@@ -85,7 +85,7 @@ export const MainThreadClient = async (
 
   let _getSignOutURLFromSessionStorage: boolean = false;
 
-  const _httpClient: HttpClientInstance = HttpClient.getInstance();
```
[the remark this answers is not in the document]
Comment (kavindadimuthu) [reply packages/browser/src/__legacy__/clients/main-thread-client.ts]: Resolved this

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts (hunk 4 above)
Comment (kavindadimuthu) [reply packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Resolved this

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 6]
```diff
@@ -59,55 +59,78 @@ export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpRe
...
+   * This should be called during provider teardown to prevent memory leaks.
+   *
+   * @param instanceId - The instance ID to destroy. Defaults to 0.
+   */
+  public static destroyInstance(instanceId: number = 0): void {
+    const axiosInstance = this.instances.get(instanceId);
+    if (axiosInstance) {
+      // Eject interceptors to prevent memory leaks
+      axiosInstance.interceptors.request.clear();
+      axiosInstance.interceptors.response.clear();
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: `destroyInstance()` is defined but **never called anywhere**. It needs to be wired into the provider teardown/unmount lifecycle (e.g., in `AsgardeoProvider`'s cleanup) to actually prevent the memory leak it was designed to address. Without a caller, this is dead code.

Please either:
1. Wire it into the provider's `useEffect` cleanup, or
2. Remove it and track the cleanup as a separate follow-up issue.

File: packages/browser/src/__legacy__/clients/web-worker-client.ts [hunk 7]
```diff
@@ -365,8 +365,8 @@ export const WebWorkerClient = async (
       }
     };
 
-    const message: Message<AuthClientConfig<WebWorkerClientConfig>> = {
-      data: config,
+    const message: Message<AuthClientConfig<WebWorkerClientConfig> & {instanceID: number}> = {
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/clients/web-worker-client.ts]: Mixing `instanceID` into the config data payload via intersection type (`& {instanceID: number}`) is fragile. If `AuthClientConfig` ever adds an `instanceID` field, it will silently conflict.

Nit: Consider passing `instanceID` as a separate field on the `Message` type rather than stuffing it into `data`.

File: packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts [hunk 8]
```diff
@@ -59,55 +59,78 @@ export class HttpClient implements HttpClientInterface<HttpRequestConfig, HttpRe
...
-   * @return {any}
+   * @param instanceId - The instance ID for multi-auth context support. Defaults to 0.
+   * @return {HttpClientInstance}
    */
-  public static getInstance(): HttpClientInstance {
-    if (this.axiosInstance) {
-      return this.axiosInstance;
+  public static getInstance(instanceId: number = 0): HttpClientInstance {
+    if (this.instances.has(instanceId)) {
+      return this.instances.get(instanceId)!;
```
Comment (DonOmalVindula) [inline packages/browser/src/__legacy__/http-client/clients/axios-http-client.ts]: Nit: Naming inconsistency — this method uses `instanceId` (camelCase) while `MainThreadClient`, `WebWorkerCore`, and `workerReceiver` all use `instanceID` (all-caps ID). Pick one convention and use it consistently across the codebase.

**Review by DonOmalVindula — CHANGES_REQUESTED** [review]
The core singleton → multiton refactoring looks correct and all previous review comments have been addressed. A few remaining items to clean up before merging.
